services:
  app:
    image: ghcr.io/igortorati/covil_trade_post_bot:latest
    container_name: tradepost-app
    restart: always
    environment:
      APP_EXPOSED_PORT: ${APP_EXPOSED_PORT}
    ports:
      - "${APP_EXPOSED_PORT:-3000}:${APP_EXPOSED_PORT:-3000}"
    command: npm run start
    stop_grace_period: 30s