version: "3.8"

services:
  app:
    build: .
    restart: always
    env_file: .env
    container_name: tradepost-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start-and-seed
