version: "3.8"

services:
  app:
    build: .
    restart: always
    env_file: .env
    container_name: tradepost-app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
    - APP_EXPOSED_PORT=${APP_EXPOSED_PORT}
    ports:
      - "${APP_EXPOSED_PORT}:${APP_EXPOSED_PORT}"
    command: npm run start
